app:
  cors:
    allowed-origins: http://192.168.1.6:3000,http://localhost:3000,http://192.168.1.2:3000
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/Security-Realm
  application:
    name: Accounting
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: hunny
    password: hunny
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: data-processing-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.ecom.accounting.Accounting.kafkaService.MeeshoPaymentDataDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.ecom.accounting.Accounting.kafkaService.MeeshoPaymentDataSerializer

file:
  upload-dir: /Users/hunnychawla/uploads
