version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
      - kafka
      - keycloak
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5433/postgres
      SPRING_DATASOURCE_USERNAME: hunny
      SPRING_DATASOURCE_PASSWORD: hunny
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KEYCLOAK_AUTH_URL: http://keycloak:8080/auth

  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: hunny
      POSTGRES_PASSWORD: hunny
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "8081:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: postgres
      DB_ADDR: db
      DB_DATABASE: mydatabase
      DB_USER: myuser
      DB_PASSWORD: mypassword

volumes:
  postgres_data:
